select * from customer_behaviour limit 5;

ALTER TABLE customer_behaviour 
RENAME COLUMN `purchase_amount_(usd)` TO purchase_amount;


-- Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue
from customer_behaviour
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount
from customer_behaviour
where purchase_amount > (select avg(purchase_amount)from customer_behaviour);

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating), 2) as average_rating
from customer_behaviour
group by item_purchased
order by average_rating desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, round(avg(purchase_amount)) as average_purchase
from customer_behaviour
where shipping_type in ('Standard', 'Express')
group by shipping_type

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
select subscription_status, 
	count(*) as total_customers, 
	round(avg(purchase_amount),2) as avg_spend, 
	round(sum(purchase_amount),2) as total_spend
from customer_behaviour
group by subscription_status

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, round(avg(case when discount_applied = 'Yes' then 1 else 0 end) * 100, 2) as discount_rate
from customer_behaviour
group by item_purchased
order by discount_rate desc
limit 5

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
select customer_segment, count(*) as number_of_customers
from
	(select customer_id, 
	previous_purchases,
    case
		when previous_purchases = 1 then 'New'
        when previous_purchases between 2 and 5 then 'Returning'
        else 'Loyal' end as customer_segment
	from customer_behaviour) as sub
group by customer_segment

-- Q8. What are the top 3 most purchased products within each category? 
with item_count as (
select category,
	item_purchased,
    count(*) as total_orders,
    row_number() over (partition by category order by count(*) desc) as item_rank
from customer_behaviour
group by category, item_purchased)

select item_rank, category, item_purchased, total_orders
from item_count
where item_rank <=3

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(*) as total_customer
from customer_behaviour
where previous_purchases > 5
group by subscription_status

-- Q10. What is the revenue contribution of each age group? 
select age_group, sum(purchase_amount) as total_revenue
from customer_behaviour
group by age_group
order by total_revenue desc